sudo: true
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
  on_success: always
  on_failure: always
node_js: '12'
install: npm install
script: npm run build && npm run cy:ci
branches:
  only: master
