sudo: true
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
    on_success: never
    on_failure: always
node_js: '10'
install: npm install
script: npm run build &&  npm run cy:ci
branches:
  only: master
